meta_product_name: "Meeter"
meta_title: "Meeter - Meet up with your friends without going a meeter too far."
meta_description: "Meeter helps you decide where to meet your friends in between two given addresses."
meta_image: "google_map_resize.png" # should exist in `app/assets/images/`
meta_type: ___
meta_url: ___
